name: ✨ Feature Request
description: Suggest an idea for textual-snapshots
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please check existing issues and discussions first.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: "I considered..."

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you would use this feature
      render: python

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: What areas would this feature affect?
      options:
        - label: CLI commands
        - label: Python API
        - label: Screenshot capture
        - label: Image comparison
        - label: Plugin system
        - label: Documentation
        - label: CI/CD integration

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request